name: CI
on: [push, pull_request]
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: ./scalafmt --test
  template-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt test
  migration-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: find migration-rules/ -mindepth 1 -maxdepth 1 -type d -execdir sh -c 'cd {} && sbt test' \;
