name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: ./scalafmt --test
  template-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: sbt test
  migration-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
      - run: ls -1 migration-rules | xargs -I{} sh -c 'cd migration-rules/{} && sbt test'
